// AUTO-GENERATED — do not edit by hand.
// Source: NOAA CO-OPS tide prediction stations, Connecticut
// Regenerate: node apps/web/scripts/generate-all-states.mjs

import type { StationConfig, NearbyStation, Species } from './florida-stations'
export type { StationConfig, NearbyStation, Species }

export const CONNECTICUT_STATIONS: StationConfig[] = [
  {
    id: "8460751", waterTempId: "8460751",
    name: "WEST MYSTIC, MYSTIC RIVER", slug: "west-mystic-mystic-river",
    state: "connecticut", city: "WEST MYSTIC, MYSTIC RIVER, CT", region: "Eastern Long Island Sound",
    lat: 41.343299865722656, lon: -71.9749984741211, latDisplay: "41.34°N", lonDisplay: "71.97°W",
    sunLat: 41.34, sunMeridian: 75, sunLon: 71.97, utcOffset: 1,
    sunriseRef: 6.52, sunsetRef: 20.25,
    tidalType: 'semidiurnal', meanRange: 4, waterTempDefault: '54°F',
    nearby: [
    { name: "NEW LONDON, State Pier", lat: 41.371667, lon: -72.095556, slug: "new-london-state-pier" },
    { name: "Yale boathouse", lat: 41.43, lon: -72.0933, slug: "yale-boathouse" },
    { name: "Niantic, Niantic River", lat: 41.325, lon: -72.1867, slug: "niantic-niantic-river" },
    { name: "Norwich", lat: 41.5233, lon: -72.0783, slug: "norwich" }
    ],
    species: [
    { name: 'Striped Bass',       icon: '🎣', color: '#38bdf8', bait: 'Live bunker, swim shad, live eel',      regulation: '28″ min · check season', when: 'Moving tide — rips, inlets & structure' },
    { name: 'Bluefish',           icon: '🐟', color: '#60a5fa', bait: 'Metal jig, popper, live bunker',         regulation: '10″ min · 10/day',       when: 'Moving tide — surface action, inlets' },
    { name: 'Summer Flounder',    icon: '🐡', color: '#34d399', bait: 'Gulp! shrimp, bucktail, spearing',       regulation: '14″ min · 10/day',       when: 'Incoming tide near channels & drop-offs' },
    { name: 'Tautog (Blackfish)', icon: '🐡', color: '#a78bfa', bait: 'Green crab, fiddler crab',               regulation: '16″ min · varies',       when: 'Slack water — wrecks, rocks, jetties' },
    { name: 'Scup (Porgy)',       icon: '🐡', color: '#facc15', bait: 'Sandworm, clam, small jig',              regulation: '9″ min · 30/day',        when: 'Incoming tide — nearshore & structure' },
  ],
  },
  {
    id: "8461392", waterTempId: "8461392",
    name: "Norwich", slug: "norwich",
    state: "connecticut", city: "Norwich, CT", region: "Central Long Island Sound",
    lat: 41.5233, lon: -72.0783, latDisplay: "41.52°N", lonDisplay: "72.08°W",
    sunLat: 41.52, sunMeridian: 75, sunLon: 72.08, utcOffset: 1,
    sunriseRef: 6.51, sunsetRef: 20.26,
    tidalType: 'semidiurnal', meanRange: 4, waterTempDefault: '54°F',
    nearby: [
    { name: "Yale boathouse", lat: 41.43, lon: -72.0933, slug: "yale-boathouse" },
    { name: "NEW LONDON, State Pier", lat: 41.371667, lon: -72.095556, slug: "new-london-state-pier" },
    { name: "WEST MYSTIC, MYSTIC RIVER", lat: 41.343299865722656, lon: -71.9749984741211, slug: "west-mystic-mystic-river" },
    { name: "Niantic, Niantic River", lat: 41.325, lon: -72.1867, slug: "niantic-niantic-river" }
    ],
    species: [
    { name: 'Striped Bass',       icon: '🎣', color: '#38bdf8', bait: 'Live bunker, swim shad, live eel',      regulation: '28″ min · check season', when: 'Moving tide — rips, inlets & structure' },
    { name: 'Bluefish',           icon: '🐟', color: '#60a5fa', bait: 'Metal jig, popper, live bunker',         regulation: '10″ min · 10/day',       when: 'Moving tide — surface action, inlets' },
    { name: 'Summer Flounder',    icon: '🐡', color: '#34d399', bait: 'Gulp! shrimp, bucktail, spearing',       regulation: '14″ min · 10/day',       when: 'Incoming tide near channels & drop-offs' },
    { name: 'Tautog (Blackfish)', icon: '🐡', color: '#a78bfa', bait: 'Green crab, fiddler crab',               regulation: '16″ min · varies',       when: 'Slack water — wrecks, rocks, jetties' },
    { name: 'Scup (Porgy)',       icon: '🐡', color: '#facc15', bait: 'Sandworm, clam, small jig',              regulation: '9″ min · 30/day',        when: 'Incoming tide — nearshore & structure' },
  ],
  },
  {
    id: "8461467", waterTempId: "8461467",
    name: "Yale boathouse", slug: "yale-boathouse",
    state: "connecticut", city: "Yale boathouse, CT", region: "Central Long Island Sound",
    lat: 41.43, lon: -72.0933, latDisplay: "41.43°N", lonDisplay: "72.09°W",
    sunLat: 41.43, sunMeridian: 75, sunLon: 72.09, utcOffset: 1,
    sunriseRef: 6.51, sunsetRef: 20.26,
    tidalType: 'semidiurnal', meanRange: 4, waterTempDefault: '54°F',
    nearby: [
    { name: "NEW LONDON, State Pier", lat: 41.371667, lon: -72.095556, slug: "new-london-state-pier" },
    { name: "Norwich", lat: 41.5233, lon: -72.0783, slug: "norwich" },
    { name: "WEST MYSTIC, MYSTIC RIVER", lat: 41.343299865722656, lon: -71.9749984741211, slug: "west-mystic-mystic-river" },
    { name: "Niantic, Niantic River", lat: 41.325, lon: -72.1867, slug: "niantic-niantic-river" }
    ],
    species: [
    { name: 'Striped Bass',       icon: '🎣', color: '#38bdf8', bait: 'Live bunker, swim shad, live eel',      regulation: '28″ min · check season', when: 'Moving tide — rips, inlets & structure' },
    { name: 'Bluefish',           icon: '🐟', color: '#60a5fa', bait: 'Metal jig, popper, live bunker',         regulation: '10″ min · 10/day',       when: 'Moving tide — surface action, inlets' },
    { name: 'Summer Flounder',    icon: '🐡', color: '#34d399', bait: 'Gulp! shrimp, bucktail, spearing',       regulation: '14″ min · 10/day',       when: 'Incoming tide near channels & drop-offs' },
    { name: 'Tautog (Blackfish)', icon: '🐡', color: '#a78bfa', bait: 'Green crab, fiddler crab',               regulation: '16″ min · varies',       when: 'Slack water — wrecks, rocks, jetties' },
    { name: 'Scup (Porgy)',       icon: '🐡', color: '#facc15', bait: 'Sandworm, clam, small jig',              regulation: '9″ min · 30/day',        when: 'Incoming tide — nearshore & structure' },
  ],
  },
  {
    id: "8461490", waterTempId: "8461490",
    name: "NEW LONDON, State Pier", slug: "new-london-state-pier",
    state: "connecticut", city: "NEW LONDON, State Pier, CT", region: "Central Long Island Sound",
    lat: 41.371667, lon: -72.095556, latDisplay: "41.37°N", lonDisplay: "72.10°W",
    sunLat: 41.37, sunMeridian: 75, sunLon: 72.1, utcOffset: 1,
    sunriseRef: 6.52, sunsetRef: 20.25,
    tidalType: 'semidiurnal', meanRange: 4, waterTempDefault: '54°F',
    nearby: [
    { name: "Yale boathouse", lat: 41.43, lon: -72.0933, slug: "yale-boathouse" },
    { name: "Niantic, Niantic River", lat: 41.325, lon: -72.1867, slug: "niantic-niantic-river" },
    { name: "WEST MYSTIC, MYSTIC RIVER", lat: 41.343299865722656, lon: -71.9749984741211, slug: "west-mystic-mystic-river" },
    { name: "Norwich", lat: 41.5233, lon: -72.0783, slug: "norwich" }
    ],
    species: [
    { name: 'Striped Bass',       icon: '🎣', color: '#38bdf8', bait: 'Live bunker, swim shad, live eel',      regulation: '28″ min · check season', when: 'Moving tide — rips, inlets & structure' },
    { name: 'Bluefish',           icon: '🐟', color: '#60a5fa', bait: 'Metal jig, popper, live bunker',         regulation: '10″ min · 10/day',       when: 'Moving tide — surface action, inlets' },
    { name: 'Summer Flounder',    icon: '🐡', color: '#34d399', bait: 'Gulp! shrimp, bucktail, spearing',       regulation: '14″ min · 10/day',       when: 'Incoming tide near channels & drop-offs' },
    { name: 'Tautog (Blackfish)', icon: '🐡', color: '#a78bfa', bait: 'Green crab, fiddler crab',               regulation: '16″ min · varies',       when: 'Slack water — wrecks, rocks, jetties' },
    { name: 'Scup (Porgy)',       icon: '🐡', color: '#facc15', bait: 'Sandworm, clam, small jig',              regulation: '9″ min · 30/day',        when: 'Incoming tide — nearshore & structure' },
  ],
  },
  {
    id: "8461925", waterTempId: "8461925",
    name: "Niantic, Niantic River", slug: "niantic-niantic-river",
    state: "connecticut", city: "Niantic, Niantic River, CT", region: "Central Long Island Sound",
    lat: 41.325, lon: -72.1867, latDisplay: "41.33°N", lonDisplay: "72.19°W",
    sunLat: 41.33, sunMeridian: 75, sunLon: 72.19, utcOffset: 1,
    sunriseRef: 6.52, sunsetRef: 20.25,
    tidalType: 'semidiurnal', meanRange: 4, waterTempDefault: '54°F',
    nearby: [
    { name: "NEW LONDON, State Pier", lat: 41.371667, lon: -72.095556, slug: "new-london-state-pier" },
    { name: "Lyme, highway bridge", lat: 41.3217, lon: -72.35, slug: "lyme-highway-bridge" },
    { name: "Yale boathouse", lat: 41.43, lon: -72.0933, slug: "yale-boathouse" },
    { name: "Saybrook Point", lat: 41.2833, lon: -72.35, slug: "saybrook-point" }
    ],
    species: [
    { name: 'Striped Bass',       icon: '🎣', color: '#38bdf8', bait: 'Live bunker, swim shad, live eel',      regulation: '28″ min · check season', when: 'Moving tide — rips, inlets & structure' },
    { name: 'Bluefish',           icon: '🐟', color: '#60a5fa', bait: 'Metal jig, popper, live bunker',         regulation: '10″ min · 10/day',       when: 'Moving tide — surface action, inlets' },
    { name: 'Summer Flounder',    icon: '🐡', color: '#34d399', bait: 'Gulp! shrimp, bucktail, spearing',       regulation: '14″ min · 10/day',       when: 'Incoming tide near channels & drop-offs' },
    { name: 'Tautog (Blackfish)', icon: '🐡', color: '#a78bfa', bait: 'Green crab, fiddler crab',               regulation: '16″ min · varies',       when: 'Slack water — wrecks, rocks, jetties' },
    { name: 'Scup (Porgy)',       icon: '🐡', color: '#facc15', bait: 'Sandworm, clam, small jig',              regulation: '9″ min · 30/day',        when: 'Incoming tide — nearshore & structure' },
  ],
  },
  {
    id: "8462723", waterTempId: "8462723",
    name: "Saybrook Jetty", slug: "saybrook-jetty",
    state: "connecticut", city: "Saybrook Jetty, CT", region: "Central Long Island Sound",
    lat: 41.2633, lon: -72.3433, latDisplay: "41.26°N", lonDisplay: "72.34°W",
    sunLat: 41.26, sunMeridian: 75, sunLon: 72.34, utcOffset: 1,
    sunriseRef: 6.52, sunsetRef: 20.25,
    tidalType: 'semidiurnal', meanRange: 4, waterTempDefault: '54°F',
    nearby: [
    { name: "Saybrook Point", lat: 41.2833, lon: -72.35, slug: "saybrook-point" },
    { name: "Lyme, highway bridge", lat: 41.3217, lon: -72.35, slug: "lyme-highway-bridge" },
    { name: "Essex", lat: 41.3483, lon: -72.385, slug: "essex" },
    { name: "Westbrook, Duck Island Roads", lat: 41.2733, lon: -72.475, slug: "westbrook-duck-island-roads" }
    ],
    species: [
    { name: 'Striped Bass',       icon: '🎣', color: '#38bdf8', bait: 'Live bunker, swim shad, live eel',      regulation: '28″ min · check season', when: 'Moving tide — rips, inlets & structure' },
    { name: 'Bluefish',           icon: '🐟', color: '#60a5fa', bait: 'Metal jig, popper, live bunker',         regulation: '10″ min · 10/day',       when: 'Moving tide — surface action, inlets' },
    { name: 'Summer Flounder',    icon: '🐡', color: '#34d399', bait: 'Gulp! shrimp, bucktail, spearing',       regulation: '14″ min · 10/day',       when: 'Incoming tide near channels & drop-offs' },
    { name: 'Tautog (Blackfish)', icon: '🐡', color: '#a78bfa', bait: 'Green crab, fiddler crab',               regulation: '16″ min · varies',       when: 'Slack water — wrecks, rocks, jetties' },
    { name: 'Scup (Porgy)',       icon: '🐡', color: '#facc15', bait: 'Sandworm, clam, small jig',              regulation: '9″ min · 30/day',        when: 'Incoming tide — nearshore & structure' },
  ],
  },
  {
    id: "8462752", waterTempId: "8462752",
    name: "Saybrook Point", slug: "saybrook-point",
    state: "connecticut", city: "Saybrook Point, CT", region: "Central Long Island Sound",
    lat: 41.2833, lon: -72.35, latDisplay: "41.28°N", lonDisplay: "72.35°W",
    sunLat: 41.28, sunMeridian: 75, sunLon: 72.35, utcOffset: 1,
    sunriseRef: 6.52, sunsetRef: 20.25,
    tidalType: 'semidiurnal', meanRange: 4, waterTempDefault: '54°F',
    nearby: [
    { name: "Saybrook Jetty", lat: 41.2633, lon: -72.3433, slug: "saybrook-jetty" },
    { name: "Lyme, highway bridge", lat: 41.3217, lon: -72.35, slug: "lyme-highway-bridge" },
    { name: "Essex", lat: 41.3483, lon: -72.385, slug: "essex" },
    { name: "Westbrook, Duck Island Roads", lat: 41.2733, lon: -72.475, slug: "westbrook-duck-island-roads" }
    ],
    species: [
    { name: 'Striped Bass',       icon: '🎣', color: '#38bdf8', bait: 'Live bunker, swim shad, live eel',      regulation: '28″ min · check season', when: 'Moving tide — rips, inlets & structure' },
    { name: 'Bluefish',           icon: '🐟', color: '#60a5fa', bait: 'Metal jig, popper, live bunker',         regulation: '10″ min · 10/day',       when: 'Moving tide — surface action, inlets' },
    { name: 'Summer Flounder',    icon: '🐡', color: '#34d399', bait: 'Gulp! shrimp, bucktail, spearing',       regulation: '14″ min · 10/day',       when: 'Incoming tide near channels & drop-offs' },
    { name: 'Tautog (Blackfish)', icon: '🐡', color: '#a78bfa', bait: 'Green crab, fiddler crab',               regulation: '16″ min · varies',       when: 'Slack water — wrecks, rocks, jetties' },
    { name: 'Scup (Porgy)',       icon: '🐡', color: '#facc15', bait: 'Sandworm, clam, small jig',              regulation: '9″ min · 30/day',        when: 'Incoming tide — nearshore & structure' },
  ],
  },
  {
    id: "8462764", waterTempId: "8462764",
    name: "Lyme, highway bridge", slug: "lyme-highway-bridge",
    state: "connecticut", city: "Lyme, highway bridge, CT", region: "Central Long Island Sound",
    lat: 41.3217, lon: -72.35, latDisplay: "41.32°N", lonDisplay: "72.35°W",
    sunLat: 41.32, sunMeridian: 75, sunLon: 72.35, utcOffset: 1,
    sunriseRef: 6.52, sunsetRef: 20.25,
    tidalType: 'semidiurnal', meanRange: 4, waterTempDefault: '54°F',
    nearby: [
    { name: "Essex", lat: 41.3483, lon: -72.385, slug: "essex" },
    { name: "Saybrook Point", lat: 41.2833, lon: -72.35, slug: "saybrook-point" },
    { name: "Saybrook Jetty", lat: 41.2633, lon: -72.3433, slug: "saybrook-jetty" },
    { name: "Westbrook, Duck Island Roads", lat: 41.2733, lon: -72.475, slug: "westbrook-duck-island-roads" }
    ],
    species: [
    { name: 'Striped Bass',       icon: '🎣', color: '#38bdf8', bait: 'Live bunker, swim shad, live eel',      regulation: '28″ min · check season', when: 'Moving tide — rips, inlets & structure' },
    { name: 'Bluefish',           icon: '🐟', color: '#60a5fa', bait: 'Metal jig, popper, live bunker',         regulation: '10″ min · 10/day',       when: 'Moving tide — surface action, inlets' },
    { name: 'Summer Flounder',    icon: '🐡', color: '#34d399', bait: 'Gulp! shrimp, bucktail, spearing',       regulation: '14″ min · 10/day',       when: 'Incoming tide near channels & drop-offs' },
    { name: 'Tautog (Blackfish)', icon: '🐡', color: '#a78bfa', bait: 'Green crab, fiddler crab',               regulation: '16″ min · varies',       when: 'Slack water — wrecks, rocks, jetties' },
    { name: 'Scup (Porgy)',       icon: '🐡', color: '#facc15', bait: 'Sandworm, clam, small jig',              regulation: '9″ min · 30/day',        when: 'Incoming tide — nearshore & structure' },
  ],
  },
  {
    id: "8462925", waterTempId: "8462925",
    name: "Essex", slug: "essex",
    state: "connecticut", city: "Essex, CT", region: "Central Long Island Sound",
    lat: 41.3483, lon: -72.385, latDisplay: "41.35°N", lonDisplay: "72.39°W",
    sunLat: 41.35, sunMeridian: 75, sunLon: 72.39, utcOffset: 1,
    sunriseRef: 6.52, sunsetRef: 20.25,
    tidalType: 'semidiurnal', meanRange: 4, waterTempDefault: '54°F',
    nearby: [
    { name: "Lyme, highway bridge", lat: 41.3217, lon: -72.35, slug: "lyme-highway-bridge" },
    { name: "Saybrook Point", lat: 41.2833, lon: -72.35, slug: "saybrook-point" },
    { name: "Hadlyme", lat: 41.42, lon: -72.4283, slug: "hadlyme" },
    { name: "Saybrook Jetty", lat: 41.2633, lon: -72.3433, slug: "saybrook-jetty" }
    ],
    species: [
    { name: 'Striped Bass',       icon: '🎣', color: '#38bdf8', bait: 'Live bunker, swim shad, live eel',      regulation: '28″ min · check season', when: 'Moving tide — rips, inlets & structure' },
    { name: 'Bluefish',           icon: '🐟', color: '#60a5fa', bait: 'Metal jig, popper, live bunker',         regulation: '10″ min · 10/day',       when: 'Moving tide — surface action, inlets' },
    { name: 'Summer Flounder',    icon: '🐡', color: '#34d399', bait: 'Gulp! shrimp, bucktail, spearing',       regulation: '14″ min · 10/day',       when: 'Incoming tide near channels & drop-offs' },
    { name: 'Tautog (Blackfish)', icon: '🐡', color: '#a78bfa', bait: 'Green crab, fiddler crab',               regulation: '16″ min · varies',       when: 'Slack water — wrecks, rocks, jetties' },
    { name: 'Scup (Porgy)',       icon: '🐡', color: '#facc15', bait: 'Sandworm, clam, small jig',              regulation: '9″ min · 30/day',        when: 'Incoming tide — nearshore & structure' },
  ],
  },
  {
    id: "8463155", waterTempId: "8463155",
    name: "Hadlyme", slug: "hadlyme",
    state: "connecticut", city: "Hadlyme, CT", region: "Central Long Island Sound",
    lat: 41.42, lon: -72.4283, latDisplay: "41.42°N", lonDisplay: "72.43°W",
    sunLat: 41.42, sunMeridian: 75, sunLon: 72.43, utcOffset: 1,
    sunriseRef: 6.51, sunsetRef: 20.26,
    tidalType: 'semidiurnal', meanRange: 4, waterTempDefault: '54°F',
    nearby: [
    { name: "Tylerville", lat: 41.4517, lon: -72.465, slug: "tylerville" },
    { name: "Essex", lat: 41.3483, lon: -72.385, slug: "essex" },
    { name: "Haddam", lat: 41.4817, lon: -72.5067, slug: "haddam" },
    { name: "Lyme, highway bridge", lat: 41.3217, lon: -72.35, slug: "lyme-highway-bridge" }
    ],
    species: [
    { name: 'Striped Bass',       icon: '🎣', color: '#38bdf8', bait: 'Live bunker, swim shad, live eel',      regulation: '28″ min · check season', when: 'Moving tide — rips, inlets & structure' },
    { name: 'Bluefish',           icon: '🐟', color: '#60a5fa', bait: 'Metal jig, popper, live bunker',         regulation: '10″ min · 10/day',       when: 'Moving tide — surface action, inlets' },
    { name: 'Summer Flounder',    icon: '🐡', color: '#34d399', bait: 'Gulp! shrimp, bucktail, spearing',       regulation: '14″ min · 10/day',       when: 'Incoming tide near channels & drop-offs' },
    { name: 'Tautog (Blackfish)', icon: '🐡', color: '#a78bfa', bait: 'Green crab, fiddler crab',               regulation: '16″ min · varies',       when: 'Slack water — wrecks, rocks, jetties' },
    { name: 'Scup (Porgy)',       icon: '🐡', color: '#facc15', bait: 'Sandworm, clam, small jig',              regulation: '9″ min · 30/day',        when: 'Incoming tide — nearshore & structure' },
  ],
  },
  {
    id: "8463348", waterTempId: "8463348",
    name: "Tylerville", slug: "tylerville",
    state: "connecticut", city: "Tylerville, CT", region: "Central Long Island Sound",
    lat: 41.4517, lon: -72.465, latDisplay: "41.45°N", lonDisplay: "72.47°W",
    sunLat: 41.45, sunMeridian: 75, sunLon: 72.47, utcOffset: 1,
    sunriseRef: 6.51, sunsetRef: 20.26,
    tidalType: 'semidiurnal', meanRange: 4, waterTempDefault: '54°F',
    nearby: [
    { name: "Hadlyme", lat: 41.42, lon: -72.4283, slug: "hadlyme" },
    { name: "Haddam", lat: 41.4817, lon: -72.5067, slug: "haddam" },
    { name: "Higganum Creek", lat: 41.5033, lon: -72.5533, slug: "higganum-creek" },
    { name: "Maromas", lat: 41.5417, lon: -72.5517, slug: "maromas" }
    ],
    species: [
    { name: 'Striped Bass',       icon: '🎣', color: '#38bdf8', bait: 'Live bunker, swim shad, live eel',      regulation: '28″ min · check season', when: 'Moving tide — rips, inlets & structure' },
    { name: 'Bluefish',           icon: '🐟', color: '#60a5fa', bait: 'Metal jig, popper, live bunker',         regulation: '10″ min · 10/day',       when: 'Moving tide — surface action, inlets' },
    { name: 'Summer Flounder',    icon: '🐡', color: '#34d399', bait: 'Gulp! shrimp, bucktail, spearing',       regulation: '14″ min · 10/day',       when: 'Incoming tide near channels & drop-offs' },
    { name: 'Tautog (Blackfish)', icon: '🐡', color: '#a78bfa', bait: 'Green crab, fiddler crab',               regulation: '16″ min · varies',       when: 'Slack water — wrecks, rocks, jetties' },
    { name: 'Scup (Porgy)',       icon: '🐡', color: '#facc15', bait: 'Sandworm, clam, small jig',              regulation: '9″ min · 30/day',        when: 'Incoming tide — nearshore & structure' },
  ],
  },
  {
    id: "8463409", waterTempId: "8463409",
    name: "Westbrook, Duck Island Roads", slug: "westbrook-duck-island-roads",
    state: "connecticut", city: "Westbrook, Duck Island Roads, CT", region: "Central Long Island Sound",
    lat: 41.2733, lon: -72.475, latDisplay: "41.27°N", lonDisplay: "72.47°W",
    sunLat: 41.27, sunMeridian: 75, sunLon: 72.47, utcOffset: 1,
    sunriseRef: 6.52, sunsetRef: 20.25,
    tidalType: 'semidiurnal', meanRange: 4, waterTempDefault: '54°F',
    nearby: [
    { name: "Clinton Harbor", lat: 41.2683, lon: -72.5317, slug: "clinton-harbor" },
    { name: "Madison", lat: 41.27, lon: -72.59, slug: "madison" },
    { name: "Saybrook Point", lat: 41.2833, lon: -72.35, slug: "saybrook-point" },
    { name: "Saybrook Jetty", lat: 41.2633, lon: -72.3433, slug: "saybrook-jetty" }
    ],
    species: [
    { name: 'Striped Bass',       icon: '🎣', color: '#38bdf8', bait: 'Live bunker, swim shad, live eel',      regulation: '28″ min · check season', when: 'Moving tide — rips, inlets & structure' },
    { name: 'Bluefish',           icon: '🐟', color: '#60a5fa', bait: 'Metal jig, popper, live bunker',         regulation: '10″ min · 10/day',       when: 'Moving tide — surface action, inlets' },
    { name: 'Summer Flounder',    icon: '🐡', color: '#34d399', bait: 'Gulp! shrimp, bucktail, spearing',       regulation: '14″ min · 10/day',       when: 'Incoming tide near channels & drop-offs' },
    { name: 'Tautog (Blackfish)', icon: '🐡', color: '#a78bfa', bait: 'Green crab, fiddler crab',               regulation: '16″ min · varies',       when: 'Slack water — wrecks, rocks, jetties' },
    { name: 'Scup (Porgy)',       icon: '🐡', color: '#facc15', bait: 'Sandworm, clam, small jig',              regulation: '9″ min · 30/day',        when: 'Incoming tide — nearshore & structure' },
  ],
  },
  {
    id: "8463582", waterTempId: "8463582",
    name: "Haddam", slug: "haddam",
    state: "connecticut", city: "Haddam, CT", region: "Central Long Island Sound",
    lat: 41.4817, lon: -72.5067, latDisplay: "41.48°N", lonDisplay: "72.51°W",
    sunLat: 41.48, sunMeridian: 75, sunLon: 72.51, utcOffset: 1,
    sunriseRef: 6.51, sunsetRef: 20.26,
    tidalType: 'semidiurnal', meanRange: 4, waterTempDefault: '54°F',
    nearby: [
    { name: "Higganum Creek", lat: 41.5033, lon: -72.5533, slug: "higganum-creek" },
    { name: "Tylerville", lat: 41.4517, lon: -72.465, slug: "tylerville" },
    { name: "Maromas", lat: 41.5417, lon: -72.5517, slug: "maromas" },
    { name: "Hadlyme", lat: 41.42, lon: -72.4283, slug: "hadlyme" }
    ],
    species: [
    { name: 'Striped Bass',       icon: '🎣', color: '#38bdf8', bait: 'Live bunker, swim shad, live eel',      regulation: '28″ min · check season', when: 'Moving tide — rips, inlets & structure' },
    { name: 'Bluefish',           icon: '🐟', color: '#60a5fa', bait: 'Metal jig, popper, live bunker',         regulation: '10″ min · 10/day',       when: 'Moving tide — surface action, inlets' },
    { name: 'Summer Flounder',    icon: '🐡', color: '#34d399', bait: 'Gulp! shrimp, bucktail, spearing',       regulation: '14″ min · 10/day',       when: 'Incoming tide near channels & drop-offs' },
    { name: 'Tautog (Blackfish)', icon: '🐡', color: '#a78bfa', bait: 'Green crab, fiddler crab',               regulation: '16″ min · varies',       when: 'Slack water — wrecks, rocks, jetties' },
    { name: 'Scup (Porgy)',       icon: '🐡', color: '#facc15', bait: 'Sandworm, clam, small jig',              regulation: '9″ min · 30/day',        when: 'Incoming tide — nearshore & structure' },
  ],
  },
  {
    id: "8463701", waterTempId: "8463701",
    name: "Clinton Harbor", slug: "clinton-harbor",
    state: "connecticut", city: "Clinton Harbor, CT", region: "Central Long Island Sound",
    lat: 41.2683, lon: -72.5317, latDisplay: "41.27°N", lonDisplay: "72.53°W",
    sunLat: 41.27, sunMeridian: 75, sunLon: 72.53, utcOffset: 1,
    sunriseRef: 6.52, sunsetRef: 20.25,
    tidalType: 'semidiurnal', meanRange: 4, waterTempDefault: '54°F',
    nearby: [
    { name: "Westbrook, Duck Island Roads", lat: 41.2733, lon: -72.475, slug: "westbrook-duck-island-roads" },
    { name: "Madison", lat: 41.27, lon: -72.59, slug: "madison" },
    { name: "Guilford Harbor", lat: 41.2717, lon: -72.6667, slug: "guilford-harbor" },
    { name: "Sachem Head", lat: 41.245, lon: -72.7083, slug: "sachem-head" }
    ],
    species: [
    { name: 'Striped Bass',       icon: '🎣', color: '#38bdf8', bait: 'Live bunker, swim shad, live eel',      regulation: '28″ min · check season', when: 'Moving tide — rips, inlets & structure' },
    { name: 'Bluefish',           icon: '🐟', color: '#60a5fa', bait: 'Metal jig, popper, live bunker',         regulation: '10″ min · 10/day',       when: 'Moving tide — surface action, inlets' },
    { name: 'Summer Flounder',    icon: '🐡', color: '#34d399', bait: 'Gulp! shrimp, bucktail, spearing',       regulation: '14″ min · 10/day',       when: 'Incoming tide near channels & drop-offs' },
    { name: 'Tautog (Blackfish)', icon: '🐡', color: '#a78bfa', bait: 'Green crab, fiddler crab',               regulation: '16″ min · varies',       when: 'Slack water — wrecks, rocks, jetties' },
    { name: 'Scup (Porgy)',       icon: '🐡', color: '#facc15', bait: 'Sandworm, clam, small jig',              regulation: '9″ min · 30/day',        when: 'Incoming tide — nearshore & structure' },
  ],
  },
  {
    id: "8463827", waterTempId: "8463827",
    name: "Maromas", slug: "maromas",
    state: "connecticut", city: "Maromas, CT", region: "Central Long Island Sound",
    lat: 41.5417, lon: -72.5517, latDisplay: "41.54°N", lonDisplay: "72.55°W",
    sunLat: 41.54, sunMeridian: 75, sunLon: 72.55, utcOffset: 1,
    sunriseRef: 6.51, sunsetRef: 20.26,
    tidalType: 'semidiurnal', meanRange: 4, waterTempDefault: '54°F',
    nearby: [
    { name: "Higganum Creek", lat: 41.5033, lon: -72.5533, slug: "higganum-creek" },
    { name: "Haddam", lat: 41.4817, lon: -72.5067, slug: "haddam" },
    { name: "Middletown", lat: 41.56, lon: -72.645, slug: "middletown" },
    { name: "Tylerville", lat: 41.4517, lon: -72.465, slug: "tylerville" }
    ],
    species: [
    { name: 'Striped Bass',       icon: '🎣', color: '#38bdf8', bait: 'Live bunker, swim shad, live eel',      regulation: '28″ min · check season', when: 'Moving tide — rips, inlets & structure' },
    { name: 'Bluefish',           icon: '🐟', color: '#60a5fa', bait: 'Metal jig, popper, live bunker',         regulation: '10″ min · 10/day',       when: 'Moving tide — surface action, inlets' },
    { name: 'Summer Flounder',    icon: '🐡', color: '#34d399', bait: 'Gulp! shrimp, bucktail, spearing',       regulation: '14″ min · 10/day',       when: 'Incoming tide near channels & drop-offs' },
    { name: 'Tautog (Blackfish)', icon: '🐡', color: '#a78bfa', bait: 'Green crab, fiddler crab',               regulation: '16″ min · varies',       when: 'Slack water — wrecks, rocks, jetties' },
    { name: 'Scup (Porgy)',       icon: '🐡', color: '#facc15', bait: 'Sandworm, clam, small jig',              regulation: '9″ min · 30/day',        when: 'Incoming tide — nearshore & structure' },
  ],
  },
  {
    id: "8463836", waterTempId: "8463836",
    name: "Higganum Creek", slug: "higganum-creek",
    state: "connecticut", city: "Higganum Creek, CT", region: "Central Long Island Sound",
    lat: 41.5033, lon: -72.5533, latDisplay: "41.50°N", lonDisplay: "72.55°W",
    sunLat: 41.5, sunMeridian: 75, sunLon: 72.55, utcOffset: 1,
    sunriseRef: 6.51, sunsetRef: 20.26,
    tidalType: 'semidiurnal', meanRange: 4, waterTempDefault: '54°F',
    nearby: [
    { name: "Maromas", lat: 41.5417, lon: -72.5517, slug: "maromas" },
    { name: "Haddam", lat: 41.4817, lon: -72.5067, slug: "haddam" },
    { name: "Tylerville", lat: 41.4517, lon: -72.465, slug: "tylerville" },
    { name: "Middletown", lat: 41.56, lon: -72.645, slug: "middletown" }
    ],
    species: [
    { name: 'Striped Bass',       icon: '🎣', color: '#38bdf8', bait: 'Live bunker, swim shad, live eel',      regulation: '28″ min · check season', when: 'Moving tide — rips, inlets & structure' },
    { name: 'Bluefish',           icon: '🐟', color: '#60a5fa', bait: 'Metal jig, popper, live bunker',         regulation: '10″ min · 10/day',       when: 'Moving tide — surface action, inlets' },
    { name: 'Summer Flounder',    icon: '🐡', color: '#34d399', bait: 'Gulp! shrimp, bucktail, spearing',       regulation: '14″ min · 10/day',       when: 'Incoming tide near channels & drop-offs' },
    { name: 'Tautog (Blackfish)', icon: '🐡', color: '#a78bfa', bait: 'Green crab, fiddler crab',               regulation: '16″ min · varies',       when: 'Slack water — wrecks, rocks, jetties' },
    { name: 'Scup (Porgy)',       icon: '🐡', color: '#facc15', bait: 'Sandworm, clam, small jig',              regulation: '9″ min · 30/day',        when: 'Incoming tide — nearshore & structure' },
  ],
  },
  {
    id: "8464041", waterTempId: "8464041",
    name: "Madison", slug: "madison",
    state: "connecticut", city: "Madison, CT", region: "Central Long Island Sound",
    lat: 41.27, lon: -72.59, latDisplay: "41.27°N", lonDisplay: "72.59°W",
    sunLat: 41.27, sunMeridian: 75, sunLon: 72.59, utcOffset: 1,
    sunriseRef: 6.52, sunsetRef: 20.25,
    tidalType: 'semidiurnal', meanRange: 4, waterTempDefault: '54°F',
    nearby: [
    { name: "Clinton Harbor", lat: 41.2683, lon: -72.5317, slug: "clinton-harbor" },
    { name: "Guilford Harbor", lat: 41.2717, lon: -72.6667, slug: "guilford-harbor" },
    { name: "Westbrook, Duck Island Roads", lat: 41.2733, lon: -72.475, slug: "westbrook-duck-island-roads" },
    { name: "Sachem Head", lat: 41.245, lon: -72.7083, slug: "sachem-head" }
    ],
    species: [
    { name: 'Striped Bass',       icon: '🎣', color: '#38bdf8', bait: 'Live bunker, swim shad, live eel',      regulation: '28″ min · check season', when: 'Moving tide — rips, inlets & structure' },
    { name: 'Bluefish',           icon: '🐟', color: '#60a5fa', bait: 'Metal jig, popper, live bunker',         regulation: '10″ min · 10/day',       when: 'Moving tide — surface action, inlets' },
    { name: 'Summer Flounder',    icon: '🐡', color: '#34d399', bait: 'Gulp! shrimp, bucktail, spearing',       regulation: '14″ min · 10/day',       when: 'Incoming tide near channels & drop-offs' },
    { name: 'Tautog (Blackfish)', icon: '🐡', color: '#a78bfa', bait: 'Green crab, fiddler crab',               regulation: '16″ min · varies',       when: 'Slack water — wrecks, rocks, jetties' },
    { name: 'Scup (Porgy)',       icon: '🐡', color: '#facc15', bait: 'Sandworm, clam, small jig',              regulation: '9″ min · 30/day',        when: 'Incoming tide — nearshore & structure' },
  ],
  },
  {
    id: "8464255", waterTempId: "8464255",
    name: "Rocky Hill", slug: "rocky-hill",
    state: "connecticut", city: "Rocky Hill, CT", region: "Central Long Island Sound",
    lat: 41.6633, lon: -72.63, latDisplay: "41.66°N", lonDisplay: "72.63°W",
    sunLat: 41.66, sunMeridian: 75, sunLon: 72.63, utcOffset: 1,
    sunriseRef: 6.5, sunsetRef: 20.27,
    tidalType: 'semidiurnal', meanRange: 4, waterTempDefault: '54°F',
    nearby: [
    { name: "South Hartford", lat: 41.755, lon: -72.6583, slug: "south-hartford" },
    { name: "Middletown", lat: 41.56, lon: -72.645, slug: "middletown" },
    { name: "Hartford", lat: 41.77, lon: -72.6683, slug: "hartford" },
    { name: "Maromas", lat: 41.5417, lon: -72.5517, slug: "maromas" }
    ],
    species: [
    { name: 'Striped Bass',       icon: '🎣', color: '#38bdf8', bait: 'Live bunker, swim shad, live eel',      regulation: '28″ min · check season', when: 'Moving tide — rips, inlets & structure' },
    { name: 'Bluefish',           icon: '🐟', color: '#60a5fa', bait: 'Metal jig, popper, live bunker',         regulation: '10″ min · 10/day',       when: 'Moving tide — surface action, inlets' },
    { name: 'Summer Flounder',    icon: '🐡', color: '#34d399', bait: 'Gulp! shrimp, bucktail, spearing',       regulation: '14″ min · 10/day',       when: 'Incoming tide near channels & drop-offs' },
    { name: 'Tautog (Blackfish)', icon: '🐡', color: '#a78bfa', bait: 'Green crab, fiddler crab',               regulation: '16″ min · varies',       when: 'Slack water — wrecks, rocks, jetties' },
    { name: 'Scup (Porgy)',       icon: '🐡', color: '#facc15', bait: 'Sandworm, clam, small jig',              regulation: '9″ min · 30/day',        when: 'Incoming tide — nearshore & structure' },
  ],
  },
  {
    id: "8464336", waterTempId: "8464336",
    name: "Middletown", slug: "middletown",
    state: "connecticut", city: "Middletown, CT", region: "Central Long Island Sound",
    lat: 41.56, lon: -72.645, latDisplay: "41.56°N", lonDisplay: "72.64°W",
    sunLat: 41.56, sunMeridian: 75, sunLon: 72.65, utcOffset: 1,
    sunriseRef: 6.51, sunsetRef: 20.26,
    tidalType: 'semidiurnal', meanRange: 4, waterTempDefault: '54°F',
    nearby: [
    { name: "Maromas", lat: 41.5417, lon: -72.5517, slug: "maromas" },
    { name: "Higganum Creek", lat: 41.5033, lon: -72.5533, slug: "higganum-creek" },
    { name: "Rocky Hill", lat: 41.6633, lon: -72.63, slug: "rocky-hill" },
    { name: "Haddam", lat: 41.4817, lon: -72.5067, slug: "haddam" }
    ],
    species: [
    { name: 'Striped Bass',       icon: '🎣', color: '#38bdf8', bait: 'Live bunker, swim shad, live eel',      regulation: '28″ min · check season', when: 'Moving tide — rips, inlets & structure' },
    { name: 'Bluefish',           icon: '🐟', color: '#60a5fa', bait: 'Metal jig, popper, live bunker',         regulation: '10″ min · 10/day',       when: 'Moving tide — surface action, inlets' },
    { name: 'Summer Flounder',    icon: '🐡', color: '#34d399', bait: 'Gulp! shrimp, bucktail, spearing',       regulation: '14″ min · 10/day',       when: 'Incoming tide near channels & drop-offs' },
    { name: 'Tautog (Blackfish)', icon: '🐡', color: '#a78bfa', bait: 'Green crab, fiddler crab',               regulation: '16″ min · varies',       when: 'Slack water — wrecks, rocks, jetties' },
    { name: 'Scup (Porgy)',       icon: '🐡', color: '#facc15', bait: 'Sandworm, clam, small jig',              regulation: '9″ min · 30/day',        when: 'Incoming tide — nearshore & structure' },
  ],
  },
  {
    id: "8464418", waterTempId: "8464418",
    name: "South Hartford", slug: "south-hartford",
    state: "connecticut", city: "South Hartford, CT", region: "Central Long Island Sound",
    lat: 41.755, lon: -72.6583, latDisplay: "41.76°N", lonDisplay: "72.66°W",
    sunLat: 41.76, sunMeridian: 75, sunLon: 72.66, utcOffset: 1,
    sunriseRef: 6.49, sunsetRef: 20.27,
    tidalType: 'semidiurnal', meanRange: 4, waterTempDefault: '54°F',
    nearby: [
    { name: "Hartford", lat: 41.77, lon: -72.6683, slug: "hartford" },
    { name: "Rocky Hill", lat: 41.6633, lon: -72.63, slug: "rocky-hill" },
    { name: "Middletown", lat: 41.56, lon: -72.645, slug: "middletown" },
    { name: "Maromas", lat: 41.5417, lon: -72.5517, slug: "maromas" }
    ],
    species: [
    { name: 'Striped Bass',       icon: '🎣', color: '#38bdf8', bait: 'Live bunker, swim shad, live eel',      regulation: '28″ min · check season', when: 'Moving tide — rips, inlets & structure' },
    { name: 'Bluefish',           icon: '🐟', color: '#60a5fa', bait: 'Metal jig, popper, live bunker',         regulation: '10″ min · 10/day',       when: 'Moving tide — surface action, inlets' },
    { name: 'Summer Flounder',    icon: '🐡', color: '#34d399', bait: 'Gulp! shrimp, bucktail, spearing',       regulation: '14″ min · 10/day',       when: 'Incoming tide near channels & drop-offs' },
    { name: 'Tautog (Blackfish)', icon: '🐡', color: '#a78bfa', bait: 'Green crab, fiddler crab',               regulation: '16″ min · varies',       when: 'Slack water — wrecks, rocks, jetties' },
    { name: 'Scup (Porgy)',       icon: '🐡', color: '#facc15', bait: 'Sandworm, clam, small jig',              regulation: '9″ min · 30/day',        when: 'Incoming tide — nearshore & structure' },
  ],
  },
  {
    id: "8464445", waterTempId: "8464445",
    name: "Guilford Harbor", slug: "guilford-harbor",
    state: "connecticut", city: "Guilford Harbor, CT", region: "Central Long Island Sound",
    lat: 41.2717, lon: -72.6667, latDisplay: "41.27°N", lonDisplay: "72.67°W",
    sunLat: 41.27, sunMeridian: 75, sunLon: 72.67, utcOffset: 1,
    sunriseRef: 6.52, sunsetRef: 20.25,
    tidalType: 'semidiurnal', meanRange: 4, waterTempDefault: '54°F',
    nearby: [
    { name: "Sachem Head", lat: 41.245, lon: -72.7083, slug: "sachem-head" },
    { name: "Madison", lat: 41.27, lon: -72.59, slug: "madison" },
    { name: "Clinton Harbor", lat: 41.2683, lon: -72.5317, slug: "clinton-harbor" },
    { name: "Branford, Branford River", lat: 41.2617, lon: -72.8183, slug: "branford-branford-river" }
    ],
    species: [
    { name: 'Striped Bass',       icon: '🎣', color: '#38bdf8', bait: 'Live bunker, swim shad, live eel',      regulation: '28″ min · check season', when: 'Moving tide — rips, inlets & structure' },
    { name: 'Bluefish',           icon: '🐟', color: '#60a5fa', bait: 'Metal jig, popper, live bunker',         regulation: '10″ min · 10/day',       when: 'Moving tide — surface action, inlets' },
    { name: 'Summer Flounder',    icon: '🐡', color: '#34d399', bait: 'Gulp! shrimp, bucktail, spearing',       regulation: '14″ min · 10/day',       when: 'Incoming tide near channels & drop-offs' },
    { name: 'Tautog (Blackfish)', icon: '🐡', color: '#a78bfa', bait: 'Green crab, fiddler crab',               regulation: '16″ min · varies',       when: 'Slack water — wrecks, rocks, jetties' },
    { name: 'Scup (Porgy)',       icon: '🐡', color: '#facc15', bait: 'Sandworm, clam, small jig',              regulation: '9″ min · 30/day',        when: 'Incoming tide — nearshore & structure' },
  ],
  },
  {
    id: "8464464", waterTempId: "8464464",
    name: "Hartford", slug: "hartford",
    state: "connecticut", city: "Hartford, CT", region: "Central Long Island Sound",
    lat: 41.77, lon: -72.6683, latDisplay: "41.77°N", lonDisplay: "72.67°W",
    sunLat: 41.77, sunMeridian: 75, sunLon: 72.67, utcOffset: 1,
    sunriseRef: 6.49, sunsetRef: 20.27,
    tidalType: 'semidiurnal', meanRange: 4, waterTempDefault: '54°F',
    nearby: [
    { name: "South Hartford", lat: 41.755, lon: -72.6583, slug: "south-hartford" },
    { name: "Rocky Hill", lat: 41.6633, lon: -72.63, slug: "rocky-hill" },
    { name: "Middletown", lat: 41.56, lon: -72.645, slug: "middletown" },
    { name: "Maromas", lat: 41.5417, lon: -72.5517, slug: "maromas" }
    ],
    species: [
    { name: 'Striped Bass',       icon: '🎣', color: '#38bdf8', bait: 'Live bunker, swim shad, live eel',      regulation: '28″ min · check season', when: 'Moving tide — rips, inlets & structure' },
    { name: 'Bluefish',           icon: '🐟', color: '#60a5fa', bait: 'Metal jig, popper, live bunker',         regulation: '10″ min · 10/day',       when: 'Moving tide — surface action, inlets' },
    { name: 'Summer Flounder',    icon: '🐡', color: '#34d399', bait: 'Gulp! shrimp, bucktail, spearing',       regulation: '14″ min · 10/day',       when: 'Incoming tide near channels & drop-offs' },
    { name: 'Tautog (Blackfish)', icon: '🐡', color: '#a78bfa', bait: 'Green crab, fiddler crab',               regulation: '16″ min · varies',       when: 'Slack water — wrecks, rocks, jetties' },
    { name: 'Scup (Porgy)',       icon: '🐡', color: '#facc15', bait: 'Sandworm, clam, small jig',              regulation: '9″ min · 30/day',        when: 'Incoming tide — nearshore & structure' },
  ],
  },
  {
    id: "8464687", waterTempId: "8464687",
    name: "Sachem Head", slug: "sachem-head",
    state: "connecticut", city: "Sachem Head, CT", region: "Central Long Island Sound",
    lat: 41.245, lon: -72.7083, latDisplay: "41.24°N", lonDisplay: "72.71°W",
    sunLat: 41.25, sunMeridian: 75, sunLon: 72.71, utcOffset: 1,
    sunriseRef: 6.53, sunsetRef: 20.25,
    tidalType: 'semidiurnal', meanRange: 4, waterTempDefault: '54°F',
    nearby: [
    { name: "Guilford Harbor", lat: 41.2717, lon: -72.6667, slug: "guilford-harbor" },
    { name: "Branford, Branford River", lat: 41.2617, lon: -72.8183, slug: "branford-branford-river" },
    { name: "Madison", lat: 41.27, lon: -72.59, slug: "madison" },
    { name: "Clinton Harbor", lat: 41.2683, lon: -72.5317, slug: "clinton-harbor" }
    ],
    species: [
    { name: 'Striped Bass',       icon: '🎣', color: '#38bdf8', bait: 'Live bunker, swim shad, live eel',      regulation: '28″ min · check season', when: 'Moving tide — rips, inlets & structure' },
    { name: 'Bluefish',           icon: '🐟', color: '#60a5fa', bait: 'Metal jig, popper, live bunker',         regulation: '10″ min · 10/day',       when: 'Moving tide — surface action, inlets' },
    { name: 'Summer Flounder',    icon: '🐡', color: '#34d399', bait: 'Gulp! shrimp, bucktail, spearing',       regulation: '14″ min · 10/day',       when: 'Incoming tide near channels & drop-offs' },
    { name: 'Tautog (Blackfish)', icon: '🐡', color: '#a78bfa', bait: 'Green crab, fiddler crab',               regulation: '16″ min · varies',       when: 'Slack water — wrecks, rocks, jetties' },
    { name: 'Scup (Porgy)',       icon: '🐡', color: '#facc15', bait: 'Sandworm, clam, small jig',              regulation: '9″ min · 30/day',        when: 'Incoming tide — nearshore & structure' },
  ],
  },
  {
    id: "8465233", waterTempId: "8465233",
    name: "Branford, Branford River", slug: "branford-branford-river",
    state: "connecticut", city: "Branford, Branford River, CT", region: "Western Long Island Sound",
    lat: 41.2617, lon: -72.8183, latDisplay: "41.26°N", lonDisplay: "72.82°W",
    sunLat: 41.26, sunMeridian: 75, sunLon: 72.82, utcOffset: 1,
    sunriseRef: 6.52, sunsetRef: 20.25,
    tidalType: 'semidiurnal', meanRange: 4, waterTempDefault: '54°F',
    nearby: [
    { name: "Lighthouse Point, New Haven Harbor", lat: 41.2517, lon: -72.905, slug: "lighthouse-point-new-haven-harbor" },
    { name: "New Haven Harbor, New Haven Reach", lat: 41.28329849243164, lon: -72.9083023071289, slug: "new-haven-harbor-new-haven-reach" },
    { name: "NEW HAVEN", lat: 41.2933, lon: -72.9167, slug: "new-haven" },
    { name: "Sachem Head", lat: 41.245, lon: -72.7083, slug: "sachem-head" }
    ],
    species: [
    { name: 'Striped Bass',       icon: '🎣', color: '#38bdf8', bait: 'Live bunker, swim shad, live eel',      regulation: '28″ min · check season', when: 'Moving tide — rips, inlets & structure' },
    { name: 'Bluefish',           icon: '🐟', color: '#60a5fa', bait: 'Metal jig, popper, live bunker',         regulation: '10″ min · 10/day',       when: 'Moving tide — surface action, inlets' },
    { name: 'Summer Flounder',    icon: '🐡', color: '#34d399', bait: 'Gulp! shrimp, bucktail, spearing',       regulation: '14″ min · 10/day',       when: 'Incoming tide near channels & drop-offs' },
    { name: 'Tautog (Blackfish)', icon: '🐡', color: '#a78bfa', bait: 'Green crab, fiddler crab',               regulation: '16″ min · varies',       when: 'Slack water — wrecks, rocks, jetties' },
    { name: 'Scup (Porgy)',       icon: '🐡', color: '#facc15', bait: 'Sandworm, clam, small jig',              regulation: '9″ min · 30/day',        when: 'Incoming tide — nearshore & structure' },
  ],
  },
  {
    id: "8465692", waterTempId: "8465692",
    name: "Lighthouse Point, New Haven Harbor", slug: "lighthouse-point-new-haven-harbor",
    state: "connecticut", city: "Lighthouse Point, New Haven Harbor, CT", region: "Western Long Island Sound",
    lat: 41.2517, lon: -72.905, latDisplay: "41.25°N", lonDisplay: "72.91°W",
    sunLat: 41.25, sunMeridian: 75, sunLon: 72.91, utcOffset: 1,
    sunriseRef: 6.52, sunsetRef: 20.25,
    tidalType: 'semidiurnal', meanRange: 4, waterTempDefault: '54°F',
    nearby: [
    { name: "New Haven Harbor, New Haven Reach", lat: 41.28329849243164, lon: -72.9083023071289, slug: "new-haven-harbor-new-haven-reach" },
    { name: "NEW HAVEN", lat: 41.2933, lon: -72.9167, slug: "new-haven" },
    { name: "Branford, Branford River", lat: 41.2617, lon: -72.8183, slug: "branford-branford-river" },
    { name: "Gulf Beach", lat: 41.205, lon: -73.0417, slug: "gulf-beach" }
    ],
    species: [
    { name: 'Striped Bass',       icon: '🎣', color: '#38bdf8', bait: 'Live bunker, swim shad, live eel',      regulation: '28″ min · check season', when: 'Moving tide — rips, inlets & structure' },
    { name: 'Bluefish',           icon: '🐟', color: '#60a5fa', bait: 'Metal jig, popper, live bunker',         regulation: '10″ min · 10/day',       when: 'Moving tide — surface action, inlets' },
    { name: 'Summer Flounder',    icon: '🐡', color: '#34d399', bait: 'Gulp! shrimp, bucktail, spearing',       regulation: '14″ min · 10/day',       when: 'Incoming tide near channels & drop-offs' },
    { name: 'Tautog (Blackfish)', icon: '🐡', color: '#a78bfa', bait: 'Green crab, fiddler crab',               regulation: '16″ min · varies',       when: 'Slack water — wrecks, rocks, jetties' },
    { name: 'Scup (Porgy)',       icon: '🐡', color: '#facc15', bait: 'Sandworm, clam, small jig',              regulation: '9″ min · 30/day',        when: 'Incoming tide — nearshore & structure' },
  ],
  },
  {
    id: "8465705", waterTempId: "8465705",
    name: "New Haven Harbor, New Haven Reach", slug: "new-haven-harbor-new-haven-reach",
    state: "connecticut", city: "New Haven Harbor, New Haven Reach, CT", region: "Western Long Island Sound",
    lat: 41.28329849243164, lon: -72.9083023071289, latDisplay: "41.28°N", lonDisplay: "72.91°W",
    sunLat: 41.28, sunMeridian: 75, sunLon: 72.91, utcOffset: 1,
    sunriseRef: 6.52, sunsetRef: 20.25,
    tidalType: 'semidiurnal', meanRange: 4, waterTempDefault: '54°F',
    nearby: [
    { name: "NEW HAVEN", lat: 41.2933, lon: -72.9167, slug: "new-haven" },
    { name: "Lighthouse Point, New Haven Harbor", lat: 41.2517, lon: -72.905, slug: "lighthouse-point-new-haven-harbor" },
    { name: "Branford, Branford River", lat: 41.2617, lon: -72.8183, slug: "branford-branford-river" },
    { name: "Shelton", lat: 41.3017, lon: -73.0717, slug: "shelton" }
    ],
    species: [
    { name: 'Striped Bass',       icon: '🎣', color: '#38bdf8', bait: 'Live bunker, swim shad, live eel',      regulation: '28″ min · check season', when: 'Moving tide — rips, inlets & structure' },
    { name: 'Bluefish',           icon: '🐟', color: '#60a5fa', bait: 'Metal jig, popper, live bunker',         regulation: '10″ min · 10/day',       when: 'Moving tide — surface action, inlets' },
    { name: 'Summer Flounder',    icon: '🐡', color: '#34d399', bait: 'Gulp! shrimp, bucktail, spearing',       regulation: '14″ min · 10/day',       when: 'Incoming tide near channels & drop-offs' },
    { name: 'Tautog (Blackfish)', icon: '🐡', color: '#a78bfa', bait: 'Green crab, fiddler crab',               regulation: '16″ min · varies',       when: 'Slack water — wrecks, rocks, jetties' },
    { name: 'Scup (Porgy)',       icon: '🐡', color: '#facc15', bait: 'Sandworm, clam, small jig',              regulation: '9″ min · 30/day',        when: 'Incoming tide — nearshore & structure' },
  ],
  },
  {
    id: "8466375", waterTempId: "8466375",
    name: "Gulf Beach", slug: "gulf-beach",
    state: "connecticut", city: "Gulf Beach, CT", region: "Western Long Island Sound",
    lat: 41.205, lon: -73.0417, latDisplay: "41.20°N", lonDisplay: "73.04°W",
    sunLat: 41.21, sunMeridian: 75, sunLon: 73.04, utcOffset: 1,
    sunriseRef: 6.53, sunsetRef: 20.25,
    tidalType: 'semidiurnal', meanRange: 4, waterTempDefault: '54°F',
    nearby: [
    { name: "Milford Harbor", lat: 41.2183, lon: -73.055, slug: "milford-harbor" },
    { name: "Stratford, I-95 bridge", lat: 41.2033, lon: -73.1117, slug: "stratford-i-95-bridge" },
    { name: "Sniffens Point", lat: 41.1867, lon: -73.1133, slug: "sniffens-point" },
    { name: "Long Hill", lat: 41.275, lon: -73.0883, slug: "long-hill" }
    ],
    species: [
    { name: 'Striped Bass',       icon: '🎣', color: '#38bdf8', bait: 'Live bunker, swim shad, live eel',      regulation: '28″ min · check season', when: 'Moving tide — rips, inlets & structure' },
    { name: 'Bluefish',           icon: '🐟', color: '#60a5fa', bait: 'Metal jig, popper, live bunker',         regulation: '10″ min · 10/day',       when: 'Moving tide — surface action, inlets' },
    { name: 'Summer Flounder',    icon: '🐡', color: '#34d399', bait: 'Gulp! shrimp, bucktail, spearing',       regulation: '14″ min · 10/day',       when: 'Incoming tide near channels & drop-offs' },
    { name: 'Tautog (Blackfish)', icon: '🐡', color: '#a78bfa', bait: 'Green crab, fiddler crab',               regulation: '16″ min · varies',       when: 'Slack water — wrecks, rocks, jetties' },
    { name: 'Scup (Porgy)',       icon: '🐡', color: '#facc15', bait: 'Sandworm, clam, small jig',              regulation: '9″ min · 30/day',        when: 'Incoming tide — nearshore & structure' },
  ],
  },
  {
    id: "8466442", waterTempId: "8466442",
    name: "Milford Harbor", slug: "milford-harbor",
    state: "connecticut", city: "Milford Harbor, CT", region: "Western Long Island Sound",
    lat: 41.2183, lon: -73.055, latDisplay: "41.22°N", lonDisplay: "73.06°W",
    sunLat: 41.22, sunMeridian: 75, sunLon: 73.06, utcOffset: 1,
    sunriseRef: 6.53, sunsetRef: 20.25,
    tidalType: 'semidiurnal', meanRange: 4, waterTempDefault: '54°F',
    nearby: [
    { name: "Gulf Beach", lat: 41.205, lon: -73.0417, slug: "gulf-beach" },
    { name: "Stratford, I-95 bridge", lat: 41.2033, lon: -73.1117, slug: "stratford-i-95-bridge" },
    { name: "Sniffens Point", lat: 41.1867, lon: -73.1133, slug: "sniffens-point" },
    { name: "Long Hill", lat: 41.275, lon: -73.0883, slug: "long-hill" }
    ],
    species: [
    { name: 'Striped Bass',       icon: '🎣', color: '#38bdf8', bait: 'Live bunker, swim shad, live eel',      regulation: '28″ min · check season', when: 'Moving tide — rips, inlets & structure' },
    { name: 'Bluefish',           icon: '🐟', color: '#60a5fa', bait: 'Metal jig, popper, live bunker',         regulation: '10″ min · 10/day',       when: 'Moving tide — surface action, inlets' },
    { name: 'Summer Flounder',    icon: '🐡', color: '#34d399', bait: 'Gulp! shrimp, bucktail, spearing',       regulation: '14″ min · 10/day',       when: 'Incoming tide near channels & drop-offs' },
    { name: 'Tautog (Blackfish)', icon: '🐡', color: '#a78bfa', bait: 'Green crab, fiddler crab',               regulation: '16″ min · varies',       when: 'Slack water — wrecks, rocks, jetties' },
    { name: 'Scup (Porgy)',       icon: '🐡', color: '#facc15', bait: 'Sandworm, clam, small jig',              regulation: '9″ min · 30/day',        when: 'Incoming tide — nearshore & structure' },
  ],
  },
  {
    id: "8466573", waterTempId: "8466573",
    name: "Shelton", slug: "shelton",
    state: "connecticut", city: "Shelton, CT", region: "Western Long Island Sound",
    lat: 41.3017, lon: -73.0717, latDisplay: "41.30°N", lonDisplay: "73.07°W",
    sunLat: 41.3, sunMeridian: 75, sunLon: 73.07, utcOffset: 1,
    sunriseRef: 6.52, sunsetRef: 20.25,
    tidalType: 'semidiurnal', meanRange: 4, waterTempDefault: '54°F',
    nearby: [
    { name: "Long Hill", lat: 41.275, lon: -73.0883, slug: "long-hill" },
    { name: "Milford Harbor", lat: 41.2183, lon: -73.055, slug: "milford-harbor" },
    { name: "Gulf Beach", lat: 41.205, lon: -73.0417, slug: "gulf-beach" },
    { name: "Stratford, I-95 bridge", lat: 41.2033, lon: -73.1117, slug: "stratford-i-95-bridge" }
    ],
    species: [
    { name: 'Striped Bass',       icon: '🎣', color: '#38bdf8', bait: 'Live bunker, swim shad, live eel',      regulation: '28″ min · check season', when: 'Moving tide — rips, inlets & structure' },
    { name: 'Bluefish',           icon: '🐟', color: '#60a5fa', bait: 'Metal jig, popper, live bunker',         regulation: '10″ min · 10/day',       when: 'Moving tide — surface action, inlets' },
    { name: 'Summer Flounder',    icon: '🐡', color: '#34d399', bait: 'Gulp! shrimp, bucktail, spearing',       regulation: '14″ min · 10/day',       when: 'Incoming tide near channels & drop-offs' },
    { name: 'Tautog (Blackfish)', icon: '🐡', color: '#a78bfa', bait: 'Green crab, fiddler crab',               regulation: '16″ min · varies',       when: 'Slack water — wrecks, rocks, jetties' },
    { name: 'Scup (Porgy)',       icon: '🐡', color: '#facc15', bait: 'Sandworm, clam, small jig',              regulation: '9″ min · 30/day',        when: 'Incoming tide — nearshore & structure' },
  ],
  },
  {
    id: "8466664", waterTempId: "8466664",
    name: "Long Hill", slug: "long-hill",
    state: "connecticut", city: "Long Hill, CT", region: "Western Long Island Sound",
    lat: 41.275, lon: -73.0883, latDisplay: "41.27°N", lonDisplay: "73.09°W",
    sunLat: 41.28, sunMeridian: 75, sunLon: 73.09, utcOffset: 1,
    sunriseRef: 6.52, sunsetRef: 20.25,
    tidalType: 'semidiurnal', meanRange: 4, waterTempDefault: '54°F',
    nearby: [
    { name: "Shelton", lat: 41.3017, lon: -73.0717, slug: "shelton" },
    { name: "Milford Harbor", lat: 41.2183, lon: -73.055, slug: "milford-harbor" },
    { name: "Stratford, I-95 bridge", lat: 41.2033, lon: -73.1117, slug: "stratford-i-95-bridge" },
    { name: "Gulf Beach", lat: 41.205, lon: -73.0417, slug: "gulf-beach" }
    ],
    species: [
    { name: 'Striped Bass',       icon: '🎣', color: '#38bdf8', bait: 'Live bunker, swim shad, live eel',      regulation: '28″ min · check season', when: 'Moving tide — rips, inlets & structure' },
    { name: 'Bluefish',           icon: '🐟', color: '#60a5fa', bait: 'Metal jig, popper, live bunker',         regulation: '10″ min · 10/day',       when: 'Moving tide — surface action, inlets' },
    { name: 'Summer Flounder',    icon: '🐡', color: '#34d399', bait: 'Gulp! shrimp, bucktail, spearing',       regulation: '14″ min · 10/day',       when: 'Incoming tide near channels & drop-offs' },
    { name: 'Tautog (Blackfish)', icon: '🐡', color: '#a78bfa', bait: 'Green crab, fiddler crab',               regulation: '16″ min · varies',       when: 'Slack water — wrecks, rocks, jetties' },
    { name: 'Scup (Porgy)',       icon: '🐡', color: '#facc15', bait: 'Sandworm, clam, small jig',              regulation: '9″ min · 30/day',        when: 'Incoming tide — nearshore & structure' },
  ],
  },
  {
    id: "8466791", waterTempId: "8466791",
    name: "Sniffens Point", slug: "sniffens-point",
    state: "connecticut", city: "Sniffens Point, CT", region: "Western Long Island Sound",
    lat: 41.1867, lon: -73.1133, latDisplay: "41.19°N", lonDisplay: "73.11°W",
    sunLat: 41.19, sunMeridian: 75, sunLon: 73.11, utcOffset: 1,
    sunriseRef: 6.53, sunsetRef: 20.25,
    tidalType: 'semidiurnal', meanRange: 4, waterTempDefault: '54°F',
    nearby: [
    { name: "Stratford, I-95 bridge", lat: 41.2033, lon: -73.1117, slug: "stratford-i-95-bridge" },
    { name: "Milford Harbor", lat: 41.2183, lon: -73.055, slug: "milford-harbor" },
    { name: "BRIDGEPORT", lat: 41.17581944444444, lon: -73.18396944444444, slug: "bridgeport" },
    { name: "Gulf Beach", lat: 41.205, lon: -73.0417, slug: "gulf-beach" }
    ],
    species: [
    { name: 'Striped Bass',       icon: '🎣', color: '#38bdf8', bait: 'Live bunker, swim shad, live eel',      regulation: '28″ min · check season', when: 'Moving tide — rips, inlets & structure' },
    { name: 'Bluefish',           icon: '🐟', color: '#60a5fa', bait: 'Metal jig, popper, live bunker',         regulation: '10″ min · 10/day',       when: 'Moving tide — surface action, inlets' },
    { name: 'Summer Flounder',    icon: '🐡', color: '#34d399', bait: 'Gulp! shrimp, bucktail, spearing',       regulation: '14″ min · 10/day',       when: 'Incoming tide near channels & drop-offs' },
    { name: 'Tautog (Blackfish)', icon: '🐡', color: '#a78bfa', bait: 'Green crab, fiddler crab',               regulation: '16″ min · varies',       when: 'Slack water — wrecks, rocks, jetties' },
    { name: 'Scup (Porgy)',       icon: '🐡', color: '#facc15', bait: 'Sandworm, clam, small jig',              regulation: '9″ min · 30/day',        when: 'Incoming tide — nearshore & structure' },
  ],
  },
  {
    id: "8466797", waterTempId: "8466797",
    name: "Stratford, I-95 bridge", slug: "stratford-i-95-bridge",
    state: "connecticut", city: "Stratford, I-95 bridge, CT", region: "Western Long Island Sound",
    lat: 41.2033, lon: -73.1117, latDisplay: "41.20°N", lonDisplay: "73.11°W",
    sunLat: 41.2, sunMeridian: 75, sunLon: 73.11, utcOffset: 1,
    sunriseRef: 6.53, sunsetRef: 20.25,
    tidalType: 'semidiurnal', meanRange: 4, waterTempDefault: '54°F',
    nearby: [
    { name: "Sniffens Point", lat: 41.1867, lon: -73.1133, slug: "sniffens-point" },
    { name: "Milford Harbor", lat: 41.2183, lon: -73.055, slug: "milford-harbor" },
    { name: "Gulf Beach", lat: 41.205, lon: -73.0417, slug: "gulf-beach" },
    { name: "BRIDGEPORT", lat: 41.17581944444444, lon: -73.18396944444444, slug: "bridgeport" }
    ],
    species: [
    { name: 'Striped Bass',       icon: '🎣', color: '#38bdf8', bait: 'Live bunker, swim shad, live eel',      regulation: '28″ min · check season', when: 'Moving tide — rips, inlets & structure' },
    { name: 'Bluefish',           icon: '🐟', color: '#60a5fa', bait: 'Metal jig, popper, live bunker',         regulation: '10″ min · 10/day',       when: 'Moving tide — surface action, inlets' },
    { name: 'Summer Flounder',    icon: '🐡', color: '#34d399', bait: 'Gulp! shrimp, bucktail, spearing',       regulation: '14″ min · 10/day',       when: 'Incoming tide near channels & drop-offs' },
    { name: 'Tautog (Blackfish)', icon: '🐡', color: '#a78bfa', bait: 'Green crab, fiddler crab',               regulation: '16″ min · varies',       when: 'Slack water — wrecks, rocks, jetties' },
    { name: 'Scup (Porgy)',       icon: '🐡', color: '#facc15', bait: 'Sandworm, clam, small jig',              regulation: '9″ min · 30/day',        when: 'Incoming tide — nearshore & structure' },
  ],
  },
  {
    id: "8467150", waterTempId: "8467150",
    name: "BRIDGEPORT", slug: "bridgeport",
    state: "connecticut", city: "BRIDGEPORT, CT", region: "Western Long Island Sound",
    lat: 41.17581944444444, lon: -73.18396944444444, latDisplay: "41.18°N", lonDisplay: "73.18°W",
    sunLat: 41.18, sunMeridian: 75, sunLon: 73.18, utcOffset: 1,
    sunriseRef: 6.53, sunsetRef: 20.25,
    tidalType: 'semidiurnal', meanRange: 4, waterTempDefault: '54°F',
    nearby: [
    { name: "Black Rock Harbor", lat: 41.1567, lon: -73.2133, slug: "black-rock-harbor" },
    { name: "Sniffens Point", lat: 41.1867, lon: -73.1133, slug: "sniffens-point" },
    { name: "Stratford, I-95 bridge", lat: 41.2033, lon: -73.1117, slug: "stratford-i-95-bridge" },
    { name: "Southport, Southport Harbor", lat: 41.1333, lon: -73.2833, slug: "southport-southport-harbor" }
    ],
    species: [
    { name: 'Striped Bass',       icon: '🎣', color: '#38bdf8', bait: 'Live bunker, swim shad, live eel',      regulation: '28″ min · check season', when: 'Moving tide — rips, inlets & structure' },
    { name: 'Bluefish',           icon: '🐟', color: '#60a5fa', bait: 'Metal jig, popper, live bunker',         regulation: '10″ min · 10/day',       when: 'Moving tide — surface action, inlets' },
    { name: 'Summer Flounder',    icon: '🐡', color: '#34d399', bait: 'Gulp! shrimp, bucktail, spearing',       regulation: '14″ min · 10/day',       when: 'Incoming tide near channels & drop-offs' },
    { name: 'Tautog (Blackfish)', icon: '🐡', color: '#a78bfa', bait: 'Green crab, fiddler crab',               regulation: '16″ min · varies',       when: 'Slack water — wrecks, rocks, jetties' },
    { name: 'Scup (Porgy)',       icon: '🐡', color: '#facc15', bait: 'Sandworm, clam, small jig',              regulation: '9″ min · 30/day',        when: 'Incoming tide — nearshore & structure' },
  ],
  },
  {
    id: "8467373", waterTempId: "8467373",
    name: "Black Rock Harbor", slug: "black-rock-harbor",
    state: "connecticut", city: "Black Rock Harbor, CT", region: "Western Long Island Sound",
    lat: 41.1567, lon: -73.2133, latDisplay: "41.16°N", lonDisplay: "73.21°W",
    sunLat: 41.16, sunMeridian: 75, sunLon: 73.21, utcOffset: 1,
    sunriseRef: 6.53, sunsetRef: 20.25,
    tidalType: 'semidiurnal', meanRange: 4, waterTempDefault: '54°F',
    nearby: [
    { name: "BRIDGEPORT", lat: 41.17581944444444, lon: -73.18396944444444, slug: "bridgeport" },
    { name: "Southport, Southport Harbor", lat: 41.1333, lon: -73.2833, slug: "southport-southport-harbor" },
    { name: "Sniffens Point", lat: 41.1867, lon: -73.1133, slug: "sniffens-point" },
    { name: "Stratford, I-95 bridge", lat: 41.2033, lon: -73.1117, slug: "stratford-i-95-bridge" }
    ],
    species: [
    { name: 'Striped Bass',       icon: '🎣', color: '#38bdf8', bait: 'Live bunker, swim shad, live eel',      regulation: '28″ min · check season', when: 'Moving tide — rips, inlets & structure' },
    { name: 'Bluefish',           icon: '🐟', color: '#60a5fa', bait: 'Metal jig, popper, live bunker',         regulation: '10″ min · 10/day',       when: 'Moving tide — surface action, inlets' },
    { name: 'Summer Flounder',    icon: '🐡', color: '#34d399', bait: 'Gulp! shrimp, bucktail, spearing',       regulation: '14″ min · 10/day',       when: 'Incoming tide near channels & drop-offs' },
    { name: 'Tautog (Blackfish)', icon: '🐡', color: '#a78bfa', bait: 'Green crab, fiddler crab',               regulation: '16″ min · varies',       when: 'Slack water — wrecks, rocks, jetties' },
    { name: 'Scup (Porgy)',       icon: '🐡', color: '#facc15', bait: 'Sandworm, clam, small jig',              regulation: '9″ min · 30/day',        when: 'Incoming tide — nearshore & structure' },
  ],
  },
  {
    id: "8467726", waterTempId: "8467726",
    name: "Southport, Southport Harbor", slug: "southport-southport-harbor",
    state: "connecticut", city: "Southport, Southport Harbor, CT", region: "Western Long Island Sound",
    lat: 41.1333, lon: -73.2833, latDisplay: "41.13°N", lonDisplay: "73.28°W",
    sunLat: 41.13, sunMeridian: 75, sunLon: 73.28, utcOffset: 1,
    sunriseRef: 6.53, sunsetRef: 20.25,
    tidalType: 'semidiurnal', meanRange: 4, waterTempDefault: '54°F',
    nearby: [
    { name: "Black Rock Harbor", lat: 41.1567, lon: -73.2133, slug: "black-rock-harbor" },
    { name: "SAUGATUCK, SAUGATUCK RIVER", lat: 41.119998931884766, lon: -73.36830139160156, slug: "saugatuck-saugatuck-river" },
    { name: "BRIDGEPORT", lat: 41.17581944444444, lon: -73.18396944444444, slug: "bridgeport" },
    { name: "South Norwalk", lat: 41.0967, lon: -73.415, slug: "south-norwalk" }
    ],
    species: [
    { name: 'Striped Bass',       icon: '🎣', color: '#38bdf8', bait: 'Live bunker, swim shad, live eel',      regulation: '28″ min · check season', when: 'Moving tide — rips, inlets & structure' },
    { name: 'Bluefish',           icon: '🐟', color: '#60a5fa', bait: 'Metal jig, popper, live bunker',         regulation: '10″ min · 10/day',       when: 'Moving tide — surface action, inlets' },
    { name: 'Summer Flounder',    icon: '🐡', color: '#34d399', bait: 'Gulp! shrimp, bucktail, spearing',       regulation: '14″ min · 10/day',       when: 'Incoming tide near channels & drop-offs' },
    { name: 'Tautog (Blackfish)', icon: '🐡', color: '#a78bfa', bait: 'Green crab, fiddler crab',               regulation: '16″ min · varies',       when: 'Slack water — wrecks, rocks, jetties' },
    { name: 'Scup (Porgy)',       icon: '🐡', color: '#facc15', bait: 'Sandworm, clam, small jig',              regulation: '9″ min · 30/day',        when: 'Incoming tide — nearshore & structure' },
  ],
  },
  {
    id: "8468191", waterTempId: "8468191",
    name: "SAUGATUCK, SAUGATUCK RIVER", slug: "saugatuck-saugatuck-river",
    state: "connecticut", city: "SAUGATUCK, SAUGATUCK RIVER, CT", region: "Western Long Island Sound",
    lat: 41.119998931884766, lon: -73.36830139160156, latDisplay: "41.12°N", lonDisplay: "73.37°W",
    sunLat: 41.12, sunMeridian: 75, sunLon: 73.37, utcOffset: 1,
    sunriseRef: 6.53, sunsetRef: 20.24,
    tidalType: 'semidiurnal', meanRange: 4, waterTempDefault: '54°F',
    nearby: [
    { name: "South Norwalk", lat: 41.0967, lon: -73.415, slug: "south-norwalk" },
    { name: "Southport, Southport Harbor", lat: 41.1333, lon: -73.2833, slug: "southport-southport-harbor" },
    { name: "Rowayton, Fivemile River", lat: 41.065, lon: -73.445, slug: "rowayton-fivemile-river" },
    { name: "Long Neck Point", lat: 41.0383, lon: -73.48, slug: "long-neck-point" }
    ],
    species: [
    { name: 'Striped Bass',       icon: '🎣', color: '#38bdf8', bait: 'Live bunker, swim shad, live eel',      regulation: '28″ min · check season', when: 'Moving tide — rips, inlets & structure' },
    { name: 'Bluefish',           icon: '🐟', color: '#60a5fa', bait: 'Metal jig, popper, live bunker',         regulation: '10″ min · 10/day',       when: 'Moving tide — surface action, inlets' },
    { name: 'Summer Flounder',    icon: '🐡', color: '#34d399', bait: 'Gulp! shrimp, bucktail, spearing',       regulation: '14″ min · 10/day',       when: 'Incoming tide near channels & drop-offs' },
    { name: 'Tautog (Blackfish)', icon: '🐡', color: '#a78bfa', bait: 'Green crab, fiddler crab',               regulation: '16″ min · varies',       when: 'Slack water — wrecks, rocks, jetties' },
    { name: 'Scup (Porgy)',       icon: '🐡', color: '#facc15', bait: 'Sandworm, clam, small jig',              regulation: '9″ min · 30/day',        when: 'Incoming tide — nearshore & structure' },
  ],
  },
  {
    id: "8468448", waterTempId: "8468448",
    name: "South Norwalk", slug: "south-norwalk",
    state: "connecticut", city: "South Norwalk, CT", region: "Western Long Island Sound",
    lat: 41.0967, lon: -73.415, latDisplay: "41.10°N", lonDisplay: "73.42°W",
    sunLat: 41.1, sunMeridian: 75, sunLon: 73.42, utcOffset: 1,
    sunriseRef: 6.53, sunsetRef: 20.24,
    tidalType: 'semidiurnal', meanRange: 4, waterTempDefault: '54°F',
    nearby: [
    { name: "Rowayton, Fivemile River", lat: 41.065, lon: -73.445, slug: "rowayton-fivemile-river" },
    { name: "SAUGATUCK, SAUGATUCK RIVER", lat: 41.119998931884766, lon: -73.36830139160156, slug: "saugatuck-saugatuck-river" },
    { name: "Long Neck Point", lat: 41.0383, lon: -73.48, slug: "long-neck-point" },
    { name: "Southport, Southport Harbor", lat: 41.1333, lon: -73.2833, slug: "southport-southport-harbor" }
    ],
    species: [
    { name: 'Striped Bass',       icon: '🎣', color: '#38bdf8', bait: 'Live bunker, swim shad, live eel',      regulation: '28″ min · check season', when: 'Moving tide — rips, inlets & structure' },
    { name: 'Bluefish',           icon: '🐟', color: '#60a5fa', bait: 'Metal jig, popper, live bunker',         regulation: '10″ min · 10/day',       when: 'Moving tide — surface action, inlets' },
    { name: 'Summer Flounder',    icon: '🐡', color: '#34d399', bait: 'Gulp! shrimp, bucktail, spearing',       regulation: '14″ min · 10/day',       when: 'Incoming tide near channels & drop-offs' },
    { name: 'Tautog (Blackfish)', icon: '🐡', color: '#a78bfa', bait: 'Green crab, fiddler crab',               regulation: '16″ min · varies',       when: 'Slack water — wrecks, rocks, jetties' },
    { name: 'Scup (Porgy)',       icon: '🐡', color: '#facc15', bait: 'Sandworm, clam, small jig',              regulation: '9″ min · 30/day',        when: 'Incoming tide — nearshore & structure' },
  ],
  },
  {
    id: "8468609", waterTempId: "8468609",
    name: "Rowayton, Fivemile River", slug: "rowayton-fivemile-river",
    state: "connecticut", city: "Rowayton, Fivemile River, CT", region: "Western Long Island Sound",
    lat: 41.065, lon: -73.445, latDisplay: "41.06°N", lonDisplay: "73.44°W",
    sunLat: 41.07, sunMeridian: 75, sunLon: 73.44, utcOffset: 1,
    sunriseRef: 6.54, sunsetRef: 20.24,
    tidalType: 'semidiurnal', meanRange: 4, waterTempDefault: '54°F',
    nearby: [
    { name: "Long Neck Point", lat: 41.0383, lon: -73.48, slug: "long-neck-point" },
    { name: "South Norwalk", lat: 41.0967, lon: -73.415, slug: "south-norwalk" },
    { name: "SAUGATUCK, SAUGATUCK RIVER", lat: 41.119998931884766, lon: -73.36830139160156, slug: "saugatuck-saugatuck-river" },
    { name: "Stamford", lat: 41.0383, lon: -73.5467, slug: "stamford" }
    ],
    species: [
    { name: 'Striped Bass',       icon: '🎣', color: '#38bdf8', bait: 'Live bunker, swim shad, live eel',      regulation: '28″ min · check season', when: 'Moving tide — rips, inlets & structure' },
    { name: 'Bluefish',           icon: '🐟', color: '#60a5fa', bait: 'Metal jig, popper, live bunker',         regulation: '10″ min · 10/day',       when: 'Moving tide — surface action, inlets' },
    { name: 'Summer Flounder',    icon: '🐡', color: '#34d399', bait: 'Gulp! shrimp, bucktail, spearing',       regulation: '14″ min · 10/day',       when: 'Incoming tide near channels & drop-offs' },
    { name: 'Tautog (Blackfish)', icon: '🐡', color: '#a78bfa', bait: 'Green crab, fiddler crab',               regulation: '16″ min · varies',       when: 'Slack water — wrecks, rocks, jetties' },
    { name: 'Scup (Porgy)',       icon: '🐡', color: '#facc15', bait: 'Sandworm, clam, small jig',              regulation: '9″ min · 30/day',        when: 'Incoming tide — nearshore & structure' },
  ],
  },
  {
    id: "8468799", waterTempId: "8468799",
    name: "Long Neck Point", slug: "long-neck-point",
    state: "connecticut", city: "Long Neck Point, CT", region: "Western Long Island Sound",
    lat: 41.0383, lon: -73.48, latDisplay: "41.04°N", lonDisplay: "73.48°W",
    sunLat: 41.04, sunMeridian: 75, sunLon: 73.48, utcOffset: 1,
    sunriseRef: 6.54, sunsetRef: 20.24,
    tidalType: 'semidiurnal', meanRange: 4, waterTempDefault: '54°F',
    nearby: [
    { name: "Rowayton, Fivemile River", lat: 41.065, lon: -73.445, slug: "rowayton-fivemile-river" },
    { name: "Stamford", lat: 41.0383, lon: -73.5467, slug: "stamford" },
    { name: "South Norwalk", lat: 41.0967, lon: -73.415, slug: "south-norwalk" },
    { name: "Mianus", lat: 41.039196, lon: -73.592026, slug: "mianus" }
    ],
    species: [
    { name: 'Striped Bass',       icon: '🎣', color: '#38bdf8', bait: 'Live bunker, swim shad, live eel',      regulation: '28″ min · check season', when: 'Moving tide — rips, inlets & structure' },
    { name: 'Bluefish',           icon: '🐟', color: '#60a5fa', bait: 'Metal jig, popper, live bunker',         regulation: '10″ min · 10/day',       when: 'Moving tide — surface action, inlets' },
    { name: 'Summer Flounder',    icon: '🐡', color: '#34d399', bait: 'Gulp! shrimp, bucktail, spearing',       regulation: '14″ min · 10/day',       when: 'Incoming tide near channels & drop-offs' },
    { name: 'Tautog (Blackfish)', icon: '🐡', color: '#a78bfa', bait: 'Green crab, fiddler crab',               regulation: '16″ min · varies',       when: 'Slack water — wrecks, rocks, jetties' },
    { name: 'Scup (Porgy)',       icon: '🐡', color: '#facc15', bait: 'Sandworm, clam, small jig',              regulation: '9″ min · 30/day',        when: 'Incoming tide — nearshore & structure' },
  ],
  },
  {
    id: "8469198", waterTempId: "8469198",
    name: "Stamford", slug: "stamford",
    state: "connecticut", city: "Stamford, CT", region: "Western Long Island Sound",
    lat: 41.0383, lon: -73.5467, latDisplay: "41.04°N", lonDisplay: "73.55°W",
    sunLat: 41.04, sunMeridian: 75, sunLon: 73.55, utcOffset: 1,
    sunriseRef: 6.54, sunsetRef: 20.24,
    tidalType: 'semidiurnal', meanRange: 4, waterTempDefault: '54°F',
    nearby: [
    { name: "Mianus", lat: 41.039196, lon: -73.592026, slug: "mianus" },
    { name: "Cos Cob Harbor", lat: 41.0167, lon: -73.5967, slug: "cos-cob-harbor" },
    { name: "Long Neck Point", lat: 41.0383, lon: -73.48, slug: "long-neck-point" },
    { name: "Rowayton, Fivemile River", lat: 41.065, lon: -73.445, slug: "rowayton-fivemile-river" }
    ],
    species: [
    { name: 'Striped Bass',       icon: '🎣', color: '#38bdf8', bait: 'Live bunker, swim shad, live eel',      regulation: '28″ min · check season', when: 'Moving tide — rips, inlets & structure' },
    { name: 'Bluefish',           icon: '🐟', color: '#60a5fa', bait: 'Metal jig, popper, live bunker',         regulation: '10″ min · 10/day',       when: 'Moving tide — surface action, inlets' },
    { name: 'Summer Flounder',    icon: '🐡', color: '#34d399', bait: 'Gulp! shrimp, bucktail, spearing',       regulation: '14″ min · 10/day',       when: 'Incoming tide near channels & drop-offs' },
    { name: 'Tautog (Blackfish)', icon: '🐡', color: '#a78bfa', bait: 'Green crab, fiddler crab',               regulation: '16″ min · varies',       when: 'Slack water — wrecks, rocks, jetties' },
    { name: 'Scup (Porgy)',       icon: '🐡', color: '#facc15', bait: 'Sandworm, clam, small jig',              regulation: '9″ min · 30/day',        when: 'Incoming tide — nearshore & structure' },
  ],
  },
  {
    id: "8469549", waterTempId: "8469549",
    name: "Cos Cob Harbor", slug: "cos-cob-harbor",
    state: "connecticut", city: "Cos Cob Harbor, CT", region: "Western Long Island Sound",
    lat: 41.0167, lon: -73.5967, latDisplay: "41.02°N", lonDisplay: "73.60°W",
    sunLat: 41.02, sunMeridian: 75, sunLon: 73.6, utcOffset: 1,
    sunriseRef: 6.54, sunsetRef: 20.24,
    tidalType: 'semidiurnal', meanRange: 4, waterTempDefault: '54°F',
    nearby: [
    { name: "Mianus", lat: 41.039196, lon: -73.592026, slug: "mianus" },
    { name: "Stamford", lat: 41.0383, lon: -73.5467, slug: "stamford" },
    { name: "Long Neck Point", lat: 41.0383, lon: -73.48, slug: "long-neck-point" },
    { name: "Rowayton, Fivemile River", lat: 41.065, lon: -73.445, slug: "rowayton-fivemile-river" }
    ],
    species: [
    { name: 'Striped Bass',       icon: '🎣', color: '#38bdf8', bait: 'Live bunker, swim shad, live eel',      regulation: '28″ min · check season', when: 'Moving tide — rips, inlets & structure' },
    { name: 'Bluefish',           icon: '🐟', color: '#60a5fa', bait: 'Metal jig, popper, live bunker',         regulation: '10″ min · 10/day',       when: 'Moving tide — surface action, inlets' },
    { name: 'Summer Flounder',    icon: '🐡', color: '#34d399', bait: 'Gulp! shrimp, bucktail, spearing',       regulation: '14″ min · 10/day',       when: 'Incoming tide near channels & drop-offs' },
    { name: 'Tautog (Blackfish)', icon: '🐡', color: '#a78bfa', bait: 'Green crab, fiddler crab',               regulation: '16″ min · varies',       when: 'Slack water — wrecks, rocks, jetties' },
    { name: 'Scup (Porgy)',       icon: '🐡', color: '#facc15', bait: 'Sandworm, clam, small jig',              regulation: '9″ min · 30/day',        when: 'Incoming tide — nearshore & structure' },
  ],
  },
  {
    id: "8465748", waterTempId: "8465748",
    name: "NEW HAVEN", slug: "new-haven",
    state: "connecticut", city: "NEW HAVEN, CT", region: "Western Long Island Sound",
    lat: 41.2933, lon: -72.9167, latDisplay: "41.29°N", lonDisplay: "72.92°W",
    sunLat: 41.29, sunMeridian: 75, sunLon: 72.92, utcOffset: 1,
    sunriseRef: 6.52, sunsetRef: 20.25,
    tidalType: 'semidiurnal', meanRange: 4, waterTempDefault: '54°F',
    nearby: [
    { name: "New Haven Harbor, New Haven Reach", lat: 41.28329849243164, lon: -72.9083023071289, slug: "new-haven-harbor-new-haven-reach" },
    { name: "Lighthouse Point, New Haven Harbor", lat: 41.2517, lon: -72.905, slug: "lighthouse-point-new-haven-harbor" },
    { name: "Branford, Branford River", lat: 41.2617, lon: -72.8183, slug: "branford-branford-river" },
    { name: "Shelton", lat: 41.3017, lon: -73.0717, slug: "shelton" }
    ],
    species: [
    { name: 'Striped Bass',       icon: '🎣', color: '#38bdf8', bait: 'Live bunker, swim shad, live eel',      regulation: '28″ min · check season', when: 'Moving tide — rips, inlets & structure' },
    { name: 'Bluefish',           icon: '🐟', color: '#60a5fa', bait: 'Metal jig, popper, live bunker',         regulation: '10″ min · 10/day',       when: 'Moving tide — surface action, inlets' },
    { name: 'Summer Flounder',    icon: '🐡', color: '#34d399', bait: 'Gulp! shrimp, bucktail, spearing',       regulation: '14″ min · 10/day',       when: 'Incoming tide near channels & drop-offs' },
    { name: 'Tautog (Blackfish)', icon: '🐡', color: '#a78bfa', bait: 'Green crab, fiddler crab',               regulation: '16″ min · varies',       when: 'Slack water — wrecks, rocks, jetties' },
    { name: 'Scup (Porgy)',       icon: '🐡', color: '#facc15', bait: 'Sandworm, clam, small jig',              regulation: '9″ min · 30/day',        when: 'Incoming tide — nearshore & structure' },
  ],
  },
  {
    id: "8469057", waterTempId: "8469057",
    name: "Mianus", slug: "mianus",
    state: "connecticut", city: "Mianus, CT", region: "Western Long Island Sound",
    lat: 41.039196, lon: -73.592026, latDisplay: "41.04°N", lonDisplay: "73.59°W",
    sunLat: 41.04, sunMeridian: 75, sunLon: 73.59, utcOffset: 1,
    sunriseRef: 6.54, sunsetRef: 20.24,
    tidalType: 'semidiurnal', meanRange: 4, waterTempDefault: '54°F',
    nearby: [
    { name: "Cos Cob Harbor", lat: 41.0167, lon: -73.5967, slug: "cos-cob-harbor" },
    { name: "Stamford", lat: 41.0383, lon: -73.5467, slug: "stamford" },
    { name: "Long Neck Point", lat: 41.0383, lon: -73.48, slug: "long-neck-point" },
    { name: "Rowayton, Fivemile River", lat: 41.065, lon: -73.445, slug: "rowayton-fivemile-river" }
    ],
    species: [
    { name: 'Striped Bass',       icon: '🎣', color: '#38bdf8', bait: 'Live bunker, swim shad, live eel',      regulation: '28″ min · check season', when: 'Moving tide — rips, inlets & structure' },
    { name: 'Bluefish',           icon: '🐟', color: '#60a5fa', bait: 'Metal jig, popper, live bunker',         regulation: '10″ min · 10/day',       when: 'Moving tide — surface action, inlets' },
    { name: 'Summer Flounder',    icon: '🐡', color: '#34d399', bait: 'Gulp! shrimp, bucktail, spearing',       regulation: '14″ min · 10/day',       when: 'Incoming tide near channels & drop-offs' },
    { name: 'Tautog (Blackfish)', icon: '🐡', color: '#a78bfa', bait: 'Green crab, fiddler crab',               regulation: '16″ min · varies',       when: 'Slack water — wrecks, rocks, jetties' },
    { name: 'Scup (Porgy)',       icon: '🐡', color: '#facc15', bait: 'Sandworm, clam, small jig',              regulation: '9″ min · 30/day',        when: 'Incoming tide — nearshore & structure' },
  ],
  },
]

export function getStationBySlug(slug: string): StationConfig | undefined {
  return CONNECTICUT_STATIONS.find(s => s.slug === slug)
}
export function getAllSlugs(): string[] {
  return CONNECTICUT_STATIONS.map(s => s.slug)
}
